name: Deploy static website

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: fly-static-site
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build and deploy static website
        working-directory: docs
        run: flyctl deploy --remote-only --ha=false --no-public-ips
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_SITE_DEPLOY_TOKEN }}
